# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _MathPython
else:
    import _MathPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Vector2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_MathPython.Vector2_x_get, _MathPython.Vector2_x_set)
    y = property(_MathPython.Vector2_y_get, _MathPython.Vector2_y_set)

    @staticmethod
    def Size():
        return _MathPython.Vector2_Size()

    def Norm(self):
        return _MathPython.Vector2_Norm(self)

    def Normalize(self):
        return _MathPython.Vector2_Normalize(self)

    @staticmethod
    def DotProduct(vec1, Row1):
        return _MathPython.Vector2_DotProduct(vec1, Row1)

    def Normal(self):
        return _MathPython.Vector2_Normal(self)

    def Angle(self, *args):
        return _MathPython.Vector2_Angle(self, *args)

    @staticmethod
    def Determinant(vec1, vec2):
        return _MathPython.Vector2_Determinant(vec1, vec2)

    @staticmethod
    def CrossProduct(vec1, vec2):
        return _MathPython.Vector2_CrossProduct(vec1, vec2)

    @staticmethod
    def DistanceSquare(a, b):
        return _MathPython.Vector2_DistanceSquare(a, b)

    @staticmethod
    def Distance(a, b):
        return _MathPython.Vector2_Distance(a, b)

    def SetPtr(self):
        return _MathPython.Vector2_SetPtr(self)

    def GetPtr(self):
        return _MathPython.Vector2_GetPtr(self)

    @staticmethod
    def Zero():
        return _MathPython.Vector2_Zero()

    @staticmethod
    def One():
        return _MathPython.Vector2_One()

    @staticmethod
    def Right():
        return _MathPython.Vector2_Right()

    @staticmethod
    def Left():
        return _MathPython.Vector2_Left()

    @staticmethod
    def Up():
        return _MathPython.Vector2_Up()

    @staticmethod
    def Down():
        return _MathPython.Vector2_Down()

    def __init__(self, *args):
        _MathPython.Vector2_swiginit(self, _MathPython.new_Vector2(*args))

    def __add__(self, *args):
        return _MathPython.Vector2___add__(self, *args)

    def __mul__(self, *args):
        return _MathPython.Vector2___mul__(self, *args)

    def __truediv__(self, *args):
        return _MathPython.Vector2___truediv__(self, *args)
    __div__ = __truediv__



    def __sub__(self, *args):
        return _MathPython.Vector2___sub__(self, *args)

    def __iadd__(self, Row1):
        return _MathPython.Vector2___iadd__(self, Row1)

    def __isub__(self, Row1):
        return _MathPython.Vector2___isub__(self, Row1)

    def __imul__(self, Row1):
        return _MathPython.Vector2___imul__(self, Row1)

    def __itruediv__(self, *args):
        return _MathPython.Vector2___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __ne__(self, vec2):
        return _MathPython.Vector2___ne__(self, vec2)

    def __eq__(self, vec2):
        return _MathPython.Vector2___eq__(self, vec2)

    def __le__(self, vec2):
        return _MathPython.Vector2___le__(self, vec2)

    def __ge__(self, vec2):
        return _MathPython.Vector2___ge__(self, vec2)

    def __getitem__(self, index):
        return _MathPython.Vector2___getitem__(self, index)

    def __setitem__(self, index, value):
        return _MathPython.Vector2___setitem__(self, index, value)
    __swig_destroy__ = _MathPython.delete_Vector2

# Register Vector2 in _MathPython:
_MathPython.Vector2_swigregister(Vector2)
class Vector3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_MathPython.Vector3_x_get, _MathPython.Vector3_x_set)
    y = property(_MathPython.Vector3_y_get, _MathPython.Vector3_y_set)
    z = property(_MathPython.Vector3_z_get, _MathPython.Vector3_z_set)

    @staticmethod
    def Size():
        return _MathPython.Vector3_Size()

    def Norm(self):
        return _MathPython.Vector3_Norm(self)

    def Normalize(self):
        return _MathPython.Vector3_Normalize(self)

    def FNorm(self):
        return _MathPython.Vector3_FNorm(self)

    def FNormalize(self):
        return _MathPython.Vector3_FNormalize(self)

    @staticmethod
    def Reflect(Vector, Normal):
        return _MathPython.Vector3_Reflect(Vector, Normal)

    @staticmethod
    def DotProduct(vec1, vec2):
        return _MathPython.Vector3_DotProduct(vec1, vec2)

    @staticmethod
    def CrossProduct(vec1, vec2):
        return _MathPython.Vector3_CrossProduct(vec1, vec2)

    @staticmethod
    def Angle(vec1, Row1):
        return _MathPython.Vector3_Angle(vec1, Row1)

    @staticmethod
    def DistanceSquare(a, b):
        return _MathPython.Vector3_DistanceSquare(a, b)

    @staticmethod
    def Distance(a, b):
        return _MathPython.Vector3_Distance(a, b)

    @staticmethod
    def scale(v, desiredLength):
        return _MathPython.Vector3_scale(v, desiredLength)

    def SetPtr(self):
        return _MathPython.Vector3_SetPtr(self)

    def GetPtr(self):
        return _MathPython.Vector3_GetPtr(self)

    def MakePositivEuleur(self):
        return _MathPython.Vector3_MakePositivEuleur(self)

    @staticmethod
    def Zero():
        return _MathPython.Vector3_Zero()

    @staticmethod
    def One():
        return _MathPython.Vector3_One()

    @staticmethod
    def Right():
        return _MathPython.Vector3_Right()

    @staticmethod
    def Left():
        return _MathPython.Vector3_Left()

    @staticmethod
    def Up():
        return _MathPython.Vector3_Up()

    @staticmethod
    def Down():
        return _MathPython.Vector3_Down()

    @staticmethod
    def Forward():
        return _MathPython.Vector3_Forward()

    @staticmethod
    def BackForward():
        return _MathPython.Vector3_BackForward()

    def __init__(self, *args):
        _MathPython.Vector3_swiginit(self, _MathPython.new_Vector3(*args))

    def __neg__(self):
        return _MathPython.Vector3___neg__(self)

    def __mul__(self, *args):
        return _MathPython.Vector3___mul__(self, *args)

    def __truediv__(self, *args):
        return _MathPython.Vector3___truediv__(self, *args)
    __div__ = __truediv__



    def __iadd__(self, Row1):
        return _MathPython.Vector3___iadd__(self, Row1)

    def __isub__(self, Row1):
        return _MathPython.Vector3___isub__(self, Row1)

    def __itruediv__(self, *args):
        return _MathPython.Vector3___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __add__(self, *args):
        return _MathPython.Vector3___add__(self, *args)

    def __sub__(self, *args):
        return _MathPython.Vector3___sub__(self, *args)

    def __imul__(self, *args):
        return _MathPython.Vector3___imul__(self, *args)

    def __getitem__(self, index):
        return _MathPython.Vector3___getitem__(self, index)

    def __setitem__(self, index, value):
        return _MathPython.Vector3___setitem__(self, index, value)
    __swig_destroy__ = _MathPython.delete_Vector3

# Register Vector3 in _MathPython:
_MathPython.Vector3_swigregister(Vector3)
class Vector4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_MathPython.Vector4_x_get, _MathPython.Vector4_x_set)
    y = property(_MathPython.Vector4_y_get, _MathPython.Vector4_y_set)
    z = property(_MathPython.Vector4_z_get, _MathPython.Vector4_z_set)
    w = property(_MathPython.Vector4_w_get, _MathPython.Vector4_w_set)

    @staticmethod
    def Size():
        return _MathPython.Vector4_Size()

    def Norm(self):
        return _MathPython.Vector4_Norm(self)

    def Normalize(self):
        return _MathPython.Vector4_Normalize(self)

    @staticmethod
    def DotProduct(vec1, vec2):
        return _MathPython.Vector4_DotProduct(vec1, vec2)

    @staticmethod
    def Angle(vec1, vec2):
        return _MathPython.Vector4_Angle(vec1, vec2)

    def __add__(self, *args):
        return _MathPython.Vector4___add__(self, *args)

    def __sub__(self, *args):
        return _MathPython.Vector4___sub__(self, *args)

    def __mul__(self, *args):
        return _MathPython.Vector4___mul__(self, *args)

    def __truediv__(self, *args):
        return _MathPython.Vector4___truediv__(self, *args)
    __div__ = __truediv__



    def __iadd__(self, value):
        return _MathPython.Vector4___iadd__(self, value)

    def __isub__(self, value):
        return _MathPython.Vector4___isub__(self, value)

    def __imul__(self, value):
        return _MathPython.Vector4___imul__(self, value)

    def __itruediv__(self, *args):
        return _MathPython.Vector4___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __neg__(self):
        return _MathPython.Vector4___neg__(self)

    @staticmethod
    def DistanceSquare(a, b):
        return _MathPython.Vector4_DistanceSquare(a, b)

    @staticmethod
    def Distance(a, b):
        return _MathPython.Vector4_Distance(a, b)

    def GetPtr(self):
        return _MathPython.Vector4_GetPtr(self)

    def SetPtr(self):
        return _MathPython.Vector4_SetPtr(self)

    @staticmethod
    def Zero():
        return _MathPython.Vector4_Zero()

    @staticmethod
    def One():
        return _MathPython.Vector4_One()

    def __init__(self, *args):
        _MathPython.Vector4_swiginit(self, _MathPython.new_Vector4(*args))

    def __getitem__(self, index):
        return _MathPython.Vector4___getitem__(self, index)

    def __setitem__(self, index, value):
        return _MathPython.Vector4___setitem__(self, index, value)
    __swig_destroy__ = _MathPython.delete_Vector4

# Register Vector4 in _MathPython:
_MathPython.Vector4_swigregister(Vector4)
class Matrix2X2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Coloms = property(_MathPython.Matrix2X2_Coloms_get, _MathPython.Matrix2X2_Coloms_set)

    @staticmethod
    def Determinant(matrix):
        return _MathPython.Matrix2X2_Determinant(matrix)

    @staticmethod
    def Size():
        return _MathPython.Matrix2X2_Size()

    @staticmethod
    def RotationMatrix2X2(angle):
        return _MathPython.Matrix2X2_RotationMatrix2X2(angle)

    def GetPtr(self):
        return _MathPython.Matrix2X2_GetPtr(self)

    def SetPtr(self):
        return _MathPython.Matrix2X2_SetPtr(self)

    def __init__(self, *args):
        _MathPython.Matrix2X2_swiginit(self, _MathPython.new_Matrix2X2(*args))

    @staticmethod
    def Identity():
        return _MathPython.Matrix2X2_Identity()
    __swig_destroy__ = _MathPython.delete_Matrix2X2

# Register Matrix2X2 in _MathPython:
_MathPython.Matrix2X2_swigregister(Matrix2X2)
class Matrix3X3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Coloms = property(_MathPython.Matrix3X3_Coloms_get, _MathPython.Matrix3X3_Coloms_set)

    @staticmethod
    def Identity():
        return _MathPython.Matrix3X3_Identity()

    @staticmethod
    def TranslationMatrix3X3(translation):
        return _MathPython.Matrix3X3_TranslationMatrix3X3(translation)

    @staticmethod
    def Rotation2DMatrix3X3(angle):
        return _MathPython.Matrix3X3_Rotation2DMatrix3X3(angle)

    def Invert(self):
        return _MathPython.Matrix3X3_Invert(self)

    def Transposate(self):
        return _MathPython.Matrix3X3_Transposate(self)

    @staticmethod
    def Determinant(matrix):
        return _MathPython.Matrix3X3_Determinant(matrix)

    @staticmethod
    def AdjoinMatrix(matrix):
        return _MathPython.Matrix3X3_AdjoinMatrix(matrix)

    def GetPtr(self):
        return _MathPython.Matrix3X3_GetPtr(self)

    def SetPtr(self):
        return _MathPython.Matrix3X3_SetPtr(self)

    def __init__(self, *args):
        _MathPython.Matrix3X3_swiginit(self, _MathPython.new_Matrix3X3(*args))

    def __mul__(self, *args):
        return _MathPython.Matrix3X3___mul__(self, *args)
    __swig_destroy__ = _MathPython.delete_Matrix3X3

# Register Matrix3X3 in _MathPython:
_MathPython.Matrix3X3_swigregister(Matrix3X3)
class Matrix4X4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Colums = property(_MathPython.Matrix4X4_Colums_get, _MathPython.Matrix4X4_Colums_set)

    def GetPos(self):
        return _MathPython.Matrix4X4_GetPos(self)

    @staticmethod
    def PerspectiveMatrix(fov, aspect, Near, Far):
        return _MathPython.Matrix4X4_PerspectiveMatrix(fov, aspect, Near, Far)

    @staticmethod
    def OrthoGraphicMatrix(left, right, bottom, top, zNear, zFar):
        return _MathPython.Matrix4X4_OrthoGraphicMatrix(left, right, bottom, top, zNear, zFar)

    @staticmethod
    def DecomposeMatrix(matrix, tranlation, rotation, scale):
        return _MathPython.Matrix4X4_DecomposeMatrix(matrix, tranlation, rotation, scale)

    @staticmethod
    def LookAt(eye, at, up):
        return _MathPython.Matrix4X4_LookAt(eye, at, up)

    @staticmethod
    def RotationZ4X4(angle):
        return _MathPython.Matrix4X4_RotationZ4X4(angle)

    @staticmethod
    def RotationY4X4(angle):
        return _MathPython.Matrix4X4_RotationY4X4(angle)

    @staticmethod
    def RotationX4X4(angle):
        return _MathPython.Matrix4X4_RotationX4X4(angle)

    @staticmethod
    def RotationMatrix4X4(angle):
        return _MathPython.Matrix4X4_RotationMatrix4X4(angle)

    @staticmethod
    def TranslateMatrix4X4(translation):
        return _MathPython.Matrix4X4_TranslateMatrix4X4(translation)

    @staticmethod
    def ScalingMatrix4X4(ScalingFactor):
        return _MathPython.Matrix4X4_ScalingMatrix4X4(ScalingFactor)

    @staticmethod
    def TRS(*args):
        return _MathPython.Matrix4X4_TRS(*args)

    @staticmethod
    def Identity():
        return _MathPython.Matrix4X4_Identity()

    def Invert(self):
        return _MathPython.Matrix4X4_Invert(self)

    def Transposate(self):
        return _MathPython.Matrix4X4_Transposate(self)

    @staticmethod
    def Determinant(matrix):
        return _MathPython.Matrix4X4_Determinant(matrix)

    def GetPtr(self):
        return _MathPython.Matrix4X4_GetPtr(self)

    def SetPtr(self):
        return _MathPython.Matrix4X4_SetPtr(self)

    @staticmethod
    def AdjoinMatrix(matrix):
        return _MathPython.Matrix4X4_AdjoinMatrix(matrix)

    def __mul__(self, *args):
        return _MathPython.Matrix4X4___mul__(self, *args)

    def __init__(self, *args):
        _MathPython.Matrix4X4_swiginit(self, _MathPython.new_Matrix4X4(*args))
    __swig_destroy__ = _MathPython.delete_Matrix4X4

# Register Matrix4X4 in _MathPython:
_MathPython.Matrix4X4_swigregister(Matrix4X4)

